name: socky_builder
description: A starting point for Dart libraries or applications.
version: 0.1.2
homepage: https://socky.dev
repository: https://github.com/redsolver/socky

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  dart_style: ^1.3.6
  socky_server: ^0.1.0
  build_resolvers: ^1.3.0
  analyzer: ">=0.37.0 <0.40.0"
  build: ^1.3.0
  source_gen: ^0.9.5
  path: ^1.6.4
  glob: ^1.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.7
  build_runner: ^1.10.0
