name: socky_cli
description: A starting point for Dart libraries or applications.
homepage: https://socky.dev
repository: https://github.com/redsolver/socky
version: 0.1.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  analyzer: ">=0.32.0 <2.0.0"
  args: ^1.0.0
  code_builder: ^3.0.0
  dart_style: ^1.0.0
  glob: ^1.1.0
  http: ^0.12.0
  io: ^0.3.2
  inflection2: ^0.4.2
  mustache4dart: ^3.0.0-dev.1.0
  path: ^1.0.0
  prompts: ^1.0.0
  pubspec_parse: ^0.1.2
  quiver: ^2.0.0
  recase: ^2.0.0
  shutdown: ^0.4.0
  watcher: ^0.9.7
  yaml: ^2.0.0

executables:
  socky: socky
